name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        cd kusto
        go get -v -t -d ./...

    - name: Build
      run: |
        cd kusto
        go build -v ./...
    - name: Test
      run: |
        cd kusto
        go test -v ./...
      env:
        ENGINE_CONNECTION_STRING: ${{ secrets.ENGINE_CONNECTION_STRING }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_KEY: ${{ secrets.APP_KEY }}
        AUTH_ID: ${{ secrets.AUTH_ID }}
        TEST_DATABASE: ${{ secrets.TEST_DATABASE }}